sudo: false
language: node_js
node_js:
  - '12'
script:
  - npm run lint
  - npm test
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm prune
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
